# Build and deploy the book to GitHub Pages

name: book

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: oven-sh/setup-bun@v2

      - name: Build Vocs
        run: cd vocs && bun install && bun run build

      # Only prepare for deploy if a push to main
      - name: Setup Pages
        if: github.ref_name == 'main' && github.event_name == 'push'
        uses: actions/configure-pages@v5

      # Only prepare for deploy if a push to main
      - name: Upload artifact
        if: github.ref_name == 'main' && github.event_name == 'push'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "vocs/docs/dist"

  deploy:
    # Only deploy if a push to main
    if: github.ref_name == 'main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: [build]

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
